name: Deploy Storybook Frontend

on:
  # Run whenever it gets pushed
  push:
    # only on changes to web
    paths:
      - 'web/**'

  # Allow running this workflow manually
  workflow_dispatch:

jobs:
  chromatic-deployment-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build Storybook
        run: yarn build:storybook
        working-directory: web

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        env:
          CHROMATIC_STORYBOOK_VERSION: react@6.3.4
        with:
          working-directory: web/storybook-static
          storybookBuildDir: web/storybook-static
          token: ${{ secrets.GH_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
